services:
  database:
    image: postgres:13-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${DATABASE_HOST_DIRECTORY}:/var/lib/postgresql/data"
      - ./database:/host
    working_dir: /host
    networks:
      - app-network

  webapp:
    image: alexgs99/node:2
    container_name: webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/electric-lounge
    working_dir: /electric-lounge/webapp
    networks:
      - app-network
    environment:
      - API_DATABASE_URL
      - LOG_CRON_PATH
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
    command: npm run dev

networks:
  app-network:
    driver: bridge
    name: electric-net
