version: '3'

vars:
  COMPOSE: docker-compose

tasks:
  config:
    cmds:
      - "{{.COMPOSE}} config"
    desc: Print the compose file with variables expanded

  down:
    cmds:
      - "{{.COMPOSE}} down --remove-orphans"
    desc: Tear down the application

  up:
    cmds:
      - "{{.COMPOSE}} up -d"
    desc: Spin-up the application
