version: '3'

dotenv: ['../.env']

vars:
  DOCKER_IMAGE: electric-lounge
  NON_LOCAL_PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
  NPM: "PATH={{.NON_LOCAL_PATH}} npm"
  VERSION:
    sh: jq -r .version ./package.json

tasks:
  build:
    cmds:
      - task: private:docker:build
      - task: private:docker:push-version
      - task: private:docker:push-latest
    desc: Build production Docker image and push to the public repository

  node:
    cmds:
      - docker exec -it webapp zsh
    desc: Open a shell for running node & npm commands in a container

  version:major:
    cmds:
      - "{{.NPM}} version major"
    desc: Increment major version number

  version:minor:
    cmds:
      - "{{.NPM}} version minor"
    desc: Increment minor version number

  version:patch:
    cmds:
      - "{{.NPM}} version patch"
    desc: Increment patch version number

  # --- PRIVATE COMMANDS ---

  private:docker:build: docker build --build-arg FONTAWESOME_NPM_AUTH_TOKEN
    -t alexgs99/{{.DOCKER_IMAGE}}:latest
    -t alexgs99/{{.DOCKER_IMAGE}}:{{.VERSION}} .

  private:docker:push-latest: docker push alexgs99/{{.DOCKER_IMAGE}}:latest

  private:docker:push-version: docker push alexgs99/{{.DOCKER_IMAGE}}:{{.VERSION}}
