version: '3'

dotenv: ['../.env']

vars:
  DOCKER_IMAGE: electric-lounge
  NPM_PATH: /usr/bin/npm
  VERSION:
    sh: jq -r .version ./package.json

tasks:
  build:
    cmds:
      - task: docker-build
      - task: docker-push-version
      - task: docker-push-latest
    desc: Build production Docker image and push to the public repository

#  fix-owner:
#    cmds:
#      - sudo chown -R alexgs:alexgs ./node_modules/@types
#    desc: Fix file owners for `node_modules/@types`

  node:
    cmds:
      - docker exec -it webapp zsh
    desc: Open a shell for running node & npm commands in a container

  version-major:
    cmds:
      - "{{.NPM_PATH}} version major"
    desc: Increment major version number

  version-minor:
    cmds:
      - "{{.NPM_PATH}} version minor"
    desc: Increment minor version number

  version-patch:
    cmds:
      - "{{.NPM_PATH}} version patch"
    desc: Increment patch version number

  # --- PRIVATE COMMANDS ---

  docker-build: docker build --build-arg FONTAWESOME_NPM_AUTH_TOKEN
    -t alexgs99/{{.DOCKER_IMAGE}}:latest
    -t alexgs99/{{.DOCKER_IMAGE}}:{{.VERSION}} .

  docker-push-latest: docker push alexgs99/{{.DOCKER_IMAGE}}:latest

  docker-push-version: docker push alexgs99/{{.DOCKER_IMAGE}}:{{.VERSION}}
